import type { IProject } from "../types"

export const projects: IProject[] = [
  {
    id: "15",
    slug: "go-kart-zen-loyalty",
    title: "Go-Kart Zen Loyalty System",
    description: "Sistema completo de gamificación y lealtad con panel de administración para gestión de recompensas y clientes.",
    longDescription:
      "Una impresionante solución frontend de control de lealtad impulsada por mecánicas de gamificación. Facilita la retención de clientes a través de un sistema de niveles VIP, membresías anuales y cupones de descuentos canjeables. El proyecto posee un módulo de simulación de base de datos con persistencia en LocalStorage para desplegar la demostración a máxima velocidad sin dependencia de backend. Incluye también un Terminal POS virtual para personalización de redenciones y registro de carreras en tiempo real.",
    image: "/project_webp/battlekart/bk1.jpg",
    images: [
      "/project_webp/battlekart/bk1.jpg",
      "/project_webp/battlekart/bk2.jpg",
      "/project_webp/battlekart/bk3.jpg",
      "/project_webp/battlekart/bk4.jpg",
      "/project_webp/battlekart/bk5.jpg",
      "/project_webp/battlekart/bk6.jpg",
    ],
    accentColor: "#EF4444",
    techStack: [
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Vite",
      "Lucide React",
      "Supabase",
    ],
    category: "Frontend",
    links: {
      live: "https://battlekarvip.drcv.site/",
      github: "https://github.com/drcvmx/battlekart-drcv",
      production: "https://battlekartvip.com/",
    },
    featured: true,
    year: 2026,
    isMobileDesign: true,
  },
  {
    id: "11",
    slug: "catalogo-alchemy",
    title: "Green Alchemy — Catálogo Digital",
    description: "Sistema de catálogo multi-sucursal con gestión de inventario y UX de alta gama.",
    longDescription: "Plataforma digital optimizada para la visualización y administración de catálogos premium en múltiples ubicaciones geográficas. Integra un panel administrativo completo con persistencia local que permite la gestión ágil de marcas, categorías y variantes.",
    image: "/project_webp/catalogo/catalogo1.png",
    images: [
      "/project_webp/catalogo/catalogo1.png",
      "/project_webp/catalogo/catalogo2.png",
      "/project_webp/catalogo/catalogo3.png",
      "/project_webp/catalogo/catalogo4.png",
    ],
    accentColor: "#10B981",
    techStack: ["React", "TypeScript", "Vite", "Tailwind CSS", "Supabase"],
    category: "Full Stack",
    links: {
      live: "https://catalogo-alchemy.drcv.site/",
      github: "https://github.com/drcvmx/catalogo-alchemy",
      production: "https://catalogo-alchemy.drcv.site/",
    },
    featured: true,
    year: 2026,
    heroImage: "/hero/catalogo.jpg",
  },
  {
    id: "12",
    slug: "balazhi-stone",
    title: "Balazhi Stone",
    description: "Exhibición premium de materiales de lujo.",
    longDescription: "Balazhi Stone es una plataforma web sofisticada diseñada para la exhibición y distribución de piedras sinterizadas, cuarzos y porcelanatos de alta gama en México. El proyecto se enfoca en una estética minimalista 'Premium Dark' con acentos dorados.",
    image: "/project_webp/balazhi/balazhi1.png",
    images: [
      "/project_webp/balazhi/balazhi1.png",
      "/project_webp/balazhi/balazhi2.png",
      "/project_webp/balazhi/balaxhi3.png",
      "/project_webp/balazhi/balazhi4.png",
    ],
    accentColor: "#D4AF37",
    techStack: ["React", "TypeScript", "Vite", "Tailwind CSS"],
    category: "Full Stack",
    links: {
      live: "https://balazhi.drcv.site/",
      github: "https://github.com/drcvmx/balazhi-for-drcv",
      production: "https://balazhistone.com/",
    },
    featured: true,
    year: 2026,
    heroImage: "/hero/balazhivertical.jpg",
  },
  {
    id: "10",
    slug: "green-alchemy-sgi",
    title: "Green Alchemy SGL",
    description: "Sistema de Gestión de Logística con arquitectura para mejorar flujos de trabajo dentro la empresa.",
    longDescription: "Un sistema avanzado de gestión de logística que centraliza los flujos de venta, tesorería y logística en una interfaz elegante y funcional. Implementa una arquitectura autónoma basada en demoStorage para garantizar persistencia y operatividad total.",
    image: "/project_webp/greensystem/green1.png",
    images: [
      "/project_webp/greensystem/green1.png",
      "/project_webp/greensystem/green2.png",
      "/project_webp/greensystem/green3.png",
      "/project_webp/greensystem/green4.png",
    ],
    accentColor: "#BFBFBF",
    techStack: ["React", "TypeScript", "Vite", "Tailwind CSS", "Supabase"],
    category: "Full Stack",
    links: {
      live: "https://greensystem.com.mx/",
      github: "https://github.com/drcvmx/greensystem-for-drcv",
      production: "https://greensystem.com.mx/",
    },
    featured: true,
    year: 2026,
    heroImage: "/hero/sgivertical.jpg",
  },
  {
    id: "9",
    slug: "one-soul-essence",
    title: "ONE · Soul Essence",
    description: "Plataforma holística premium para el bienestar personal y la conexión espiritual profunda.",
    longDescription: "Una experiencia digital integral que fusiona una boutique de cristales curativos, un centro de formación espiritual y un catálogo de terapias y retiros sagrados. Diseñada con una estética elegante y minimalista, la plataforma ofrece una navegación fluida con efectos de paralaje y persistencia de datos local.",
    image: "/project_webp/one/one1.png",
    images: [
      "/project_webp/one/one1.png",
      "/project_webp/one/one2.png",
      "/project_webp/one/one3.png",
      "/project_webp/one/one4.png",
    ],
    accentColor: "#8d288e",
    techStack: ["React", "TypeScript", "Vite", "Tailwind CSS", "Supabase"],
    category: "Full Stack",
    links: {
      live: "https://one.drcv.site/",
      github: "https://github.com/drcvmx/onefordrcv",
      production: "https://onesomosuno.com/",
    },
    featured: true,
    year: 2026,
    heroImage: "/hero/onevertical.jpg",
  },
  {
    id: "14",
    slug: "probin-real-estate-cms",
    title: "Probin Real Estate CMS",
    description: "Plataforma premium para la exhibición de desarrollos inmobiliarios y gestión integral interactiva de CRM.",
    longDescription:
      "Una solución frontend de alto nivel que combina un portal inmersivo para la presentación de múltiples proyectos inmobiliarios con un potente panel administrativo. Permite a los agentes gestionar leads, citas, perfiles de clientes, campañas y checklists de cierre operativo. Está impulsada por un MockDB basado en LocalStorage, garantizando demostraciones de ventas ultrarrápidas, persistencia de datos offline y una experiencia visual fluida sin dependencia de un backend tradicional.",
    image: "/project_webp/probin/hero-probin-mobile.jpg",
    images: [
      "/project_webp/probin/probin1.png",
      "/project_webp/probin/probin2.png",
      "/project_webp/probin/probin3.png",
      "/project_webp/probin/probin4.png",
    ],
    accentColor: "#3B82F6",
    techStack: [
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Lucide React",
      "Supabase",
    ],
    category: "Frontend",
    links: {
      live: "https://probin.drcv.site/",
      github: "https://github.com/drcvmx/probin-for-dante",
      production: "https://probinrealestate.com/",
    },
    featured: true,
    year: 2026,
    heroImage: "/project_webp/probin/hero-probin-mobile.jpg",
    isMobileDesign: true,
  },
  {
    id: "1",
    slug: "winpot-cms-multi-tenant",
    title: "Winpot CMS & Multi-Tenant",
    description: "CMS multi-tenant de alto rendimiento para la gestión dinámica de casinos y contenido gamificado.",
    longDescription: "Una solución robusta para redes de casinos que centraliza la administración de múltiples identidades de marca en un solo núcleo técnico. Implementa un sistema de diseño atómico y arquitectura basada en tenants para ofrecer experiencias personalizadas.",
    image: "/project_webp/winpot/winpot1.png",
    images: [
      "/project_webp/winpot/winpot1.png",
      "/project_webp/winpot/winport21.png",
      "/project_webp/winpot/winport3.1.png",
      "/project_webp/winpot/winpot4.png",
    ],
    accentColor: "#D4AF37",
    techStack: ["React", "TypeScript", "Tailwind CSS", "Supabase"],
    category: "Full Stack",
    links: {
      live: "http://winpot.drcv.site/",
      github: "https://github.com/drcvmx/winpotfordrcv",
      production: "https://winpotsetup.com/",
    },
    featured: false,
    year: 2026,
  },
  {
    id: "2",
    slug: "seprytec",
    title: "seprytec",
    description: "Sitio web moderno para una empresa de seguridad privada.",
    longDescription:
      "Sitio web moderno para una empresa de seguridad privada. Diseñado para infundir confianza a través de un diseño intuitivo y navegación fluida.",
    image: "/project_webp/seprytec/seprytec1.webp",
    images: [
      "/project_webp/seprytec/seprytec1.webp",
      "/project_webp/seprytec/seprytec2.webp",
      "/project_webp/seprytec/seprytec3.webp",
    ],
    accentColor: "#ff3366",
    techStack: ["Next.js", "React", "Tailwind CSS", "JavaScript"],
    category: "Full Stack",
    links: {
      live: "https://seprytec.drcv.site/",
      github: "https://github.com/drcvmx/seprytec_remaster",
      production: "https://seprytec.drcv.site/",
    },
    featured: false,
    year: 2024,
  },
  {
    id: "13",
    slug: "drcv-company",
    title: "drcv_company",
    description: "Sitio web corporativo moderno diseñado para impulsar la presencia en línea de las empresas.",
    longDescription:
      "Un sitio web corporativo moderno diseñado para impulsar la presencia en línea de las empresas. Optimizado para eficiencia y experiencia de usuario, utilizando Astro para rendimiento y Vue.js para interactividad.",
    image: "/project_webp/drcv_company/company1.webp",
    images: [
      "/project_webp/drcv_company/company1.webp",
      "/project_webp/drcv_company/company2.webp",
      "/project_webp/drcv_company/company3.webp",
    ],
    accentColor: "#5D3FD3",
    techStack: ["Astro", "Vue.js", "SCSS", "TypeScript"],
    category: "Full Stack",
    links: {
      live: "https://drcv-company.drcv.site/",
      github: "https://github.com/drcvmx/drcv_company",
      production: "https://drcv-company.drcv.site/",
    },
    featured: false,
    year: 2024,
  },
  {
    id: "8",
    slug: "youtube-transcribe",
    title: "youtube_transcribe",
    description: "Aplicación web que extrae y analiza el contenido de videos de YouTube.",
    longDescription:
      "Aplicación web que extrae y analiza el contenido de videos de YouTube. Utiliza un backend en Python para obtener transcripciones y un modelo de lenguaje (Ollama) para procesar y resumir el texto.",
    image: "/project_webp/youtube_transcribe/transcribe1.webp",
    images: [
      "/project_webp/youtube_transcribe/transcribe1.webp",
    ],
    accentColor: "#ff3366",
    techStack: ["React", "Next.js", "JavaScript", "Python", "Flask"],
    category: "Full Stack",
    links: {
      live: "#",
      github: "https://github.com/drcvmx",
      production: "#",
    },
    featured: false,
    year: 2024,
  },
]
